ch8_cmd := ch8/cmd
ch5_cmd := ch5/cmd

.PHONY: findlinks1
findlinks1:
	go build -o build/findlinks1 $(ch5_cmd)/findlinks1/main.go

.PHONY: findlinksr
findlinksr:
	go build -o build/findlinksr $(ch5_cmd)/findlinksr/main.go


.PHONY: clock1
clock1:
	go build -o build/clock1 $(ch8_cmd)/clock1/main.go

.PHONY: clock2
clock2:
	go build -o build/clock2 $(ch8_cmd)/clock2/main.go

.PHONY: netcat1
netcat1:
	go build -o build/netcat1 $(ch8_cmd)/netcat1/main.go

.PHONY: clockwall
clockwall:
	go build -o build/clockwall $(ch8_cmd)/clockwall/main.go

.PHONY: ftp
ftp:
	go build -o build/ftp $(ch8_cmd)/ftp/main.go

.PHONY: reverb1
reverb1:
	go build -o build/reverb1 $(ch8_cmd)/reverb1/main.go


.PHONY: netcat2
netcat2:
	go build -o build/netcat2 $(ch8_cmd)/netcat2/main.go

.PHONY: reverb2
reverb2:
	go build -o build/reverb2 $(ch8_cmd)/reverb2/main.go