ch8_cmd := ch8/cmd
ch5_cmd := ch5/cmd

.PHONY: findlinks1
findlinks1:
	go build -o build/findlinks1 $(ch5_cmd)/findlinks1/main.go

.PHONY: findlinksr
findlinksr:
	go build -o build/findlinksr $(ch5_cmd)/findlinksr/main.go

.PHONY: outline
outline:
	go build -o build/outline $(ch5_cmd)/outline/main.go

.PHONY: countname
countname:
	go build -o build/countname $(ch5_cmd)/countname/main.go

.PHONY: showtext
showtext:
	go build -o build/showtext $(ch5_cmd)/showtext/main.go

.PHONY: findlinksall
findlinksall:
	go build -o build/findlinksall $(ch5_cmd)/findlinksall/main.go

.PHONY: findlinks2
findlinks2:
	go build -o build/findlinks2 $(ch5_cmd)/findlinks2/main.go

.PHONY: countwords
countwords:
	go build -o build/countwords $(ch5_cmd)/countwords/main.go

.PHONY: outline2
outline2:
	go build -o build/outline2 $(ch5_cmd)/outline2/main.go

.PHONY: findid
findid:
	go build -o build/findid $(ch5_cmd)/findid/main.go

.PHONY: findlinks3
findlinks3:
	go build -o build/findlinks3 $(ch5_cmd)/findlinks3/main.go

.PHONY: clock1
clock1:
	go build -o build/clock1 $(ch8_cmd)/clock1/main.go

.PHONY: clock2
clock2:
	go build -o build/clock2 $(ch8_cmd)/clock2/main.go

.PHONY: netcat1
netcat1:
	go build -o build/netcat1 $(ch8_cmd)/netcat1/main.go

.PHONY: clockwall
clockwall:
	go build -o build/clockwall $(ch8_cmd)/clockwall/main.go

.PHONY: ftp
ftp:
	go build -o build/ftp $(ch8_cmd)/ftp/main.go

.PHONY: reverb1
reverb1:
	go build -o build/reverb1 $(ch8_cmd)/reverb1/main.go


.PHONY: netcat2
netcat2:
	go build -o build/netcat2 $(ch8_cmd)/netcat2/main.go

.PHONY: reverb2
reverb2:
	go build -o build/reverb2 $(ch8_cmd)/reverb2/main.go